### PR TITLE
Add CMake build system

### PR DESCRIPTION
**Pull request by pschella**
Adds a minimal CMake build system next to the existing SCons based one.

### CODE REVIEW

**Comment by TallJimbo** [comment]
I accepted a PR a while ago an Boost.NumPy to move from `FindPythonLibsNew` to just `FindPythonLibs`: https://github.com/ndarray/Boost.NumPy/pull/56.

Do you have any reason to think `FindPythonLibsNew` is still necessary?

**Comment by pschella** [comment]
No, no reason. Removed it now.

**Comment by TallJimbo** [comment]
I've added another commit to the PR to mention the cmake build (and the caveat about lack of Boost.NumPy support) in the README.  With that, I'm happy to merge this, though squashing might be a good idea. Anything else you want to do first?

**Comment by pschella** [comment]
Seems ready for merge. And tag as version 1.1.0 for LSST purposes?

**Comment by TallJimbo** [comment]
Yup, go ahead and merge.  You may want to hold off on tagging until you've got the full LSST stack working with it, but if tagging early is helpful in getting to that state, go ahead with that too; numbers are cheap.

**Comment by pschella** [comment]
Yes, the full stack already works. So merging now.

**Pull request merged**
