### PR TITLE
use modern cmake; clean up doxygen generation

### PR DESCRIPTION
**Pull request by mwittgen**
remove cmake find package support from ndarray.
fftw cmake support is broken:  https://github.com/FFTW/fftw3/issues/130 revert to cmake pkg support.

### CODE REVIEW

**Review by TallJimbo — COMMENTED** [review]
Code all looks good to me, but I've run into some trouble testing the changes locally (via the same conda environment I've used successfully in the past).

In particular, it seems to succeed when running cmake (or at least doesn't clearly fail), but later fails when actually building the test binaries, as it can't link against fftw:
```
$ cmake .. -D NDARRAY_PYBIND11=ON
-- The CXX compiler identification is GNU 9.3.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Found Boost: /home/jbosch/LSST/lsstsw/miniconda/envs/ndarray/lib/cmake/Boost-1.74.0/BoostConfig.cmake (found version "1.74.0") found components: unit_test_framework 
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for one of the modules 'fftw3'
-- Found PythonInterp: /home/jbosch/LSST/lsstsw/miniconda/envs/ndarray/bin/python (found version "3.8.5") 
-- Found PythonLibs: /home/jbosch/LSST/lsstsw/miniconda/envs/ndarray/lib/libpython3.8.so (found version "3.8.5") 
-- Found PythonLibs: /home/jbosch/LSST/lsstsw/miniconda/envs/ndarray/lib/libpython3.8.so
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- Found pybind11: /home/jbosch/LSST/lsstsw/miniconda/envs/ndarray/include (found version "2.6.1" )
-- Configuring done
-- Generating done
-- Build files have been written to: /home/jbosch/ndarray/ndarray/build
14:36 $ make
Scanning dependencies of target pybind11_test_mod
[ 10%] Building CXX object tests/CMakeFiles/pybind11_test_mod.dir/pybind11_test_mod.cc.o
[ 20%] Linking CXX shared module pybind11_test_mod.cpython-38-x86_64-linux-gnu.so
[ 20%] Built target pybind11_test_mod
Scanning dependencies of target ndarray-eigen
[ 30%] Building CXX object tests/CMakeFiles/ndarray-eigen.dir/ndarray-eigen.cc.o
[ 40%] Linking CXX executable ndarray-eigen
[ 40%] Built target ndarray-eigen
Scanning dependencies of target ndarray-fft
[ 50%] Building CXX object tests/CMakeFiles/ndarray-fft.dir/ndarray-fft.cc.o
[ 60%] Linking CXX executable ndarray-fft
/usr/bin/ld: cannot find -lfftw3
collect2: error: ld returned 1 exit status
make[2]: *** [tests/CMakeFiles/ndarray-fft.dir/build.make:104: tests/ndarray-fft] Error 1
make[1]: *** [CMakeFiles/Makefile2:196: tests/CMakeFiles/ndarray-fft.dir/all] Error 2
make: *** [Makefile:160: all] Error 2
```
But I can't see anything that I'm doing that's meaningfully different from the CI script (`.github/workflows/build.yaml`), and that seems to have past.

Well, not quite - in the CI script, I'm actually passing a few more `-D` options to cmake, but of those:
 - `-DCMAKE_PREFIX_PATH=$CONDA_PREFIX`: doesn't change what I get; it seems to (now) work fine without it;
 - `-DCMAKE_BUILD_TYPE=Release`: this doesn't (and shouldn't) matter for dependency logic;
 - `-D Boost_NO_BOOST_CMAKE=ON`: this should no longer be necessary after the changes on this branch, and I'd like to remove it on this branch (it was a workaround for ndarray's cmake build being too old before).  And if I _add_ it locally, I actually get what looks like failures when running `cmake`, but it seems to continue anyway:
```
 cmake .. -DCMAKE_BUILD_TYPE=Release -D Boost_NO_BOOST_CMAKE=ON -DNDARRAY_PYBIND11=ON -DCMAKE_PREFIX_PATH=$CONDA_PREFIX
-- The CXX compiler identification is GNU 9.3.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
CMake Warning at /home/jbosch/LSST/lsstsw/miniconda/envs/ndarray/share/cmake-3.18/Modules/FindBoost.cmake:1187 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /home/jbosch/LSST/lsstsw/miniconda/envs/ndarray/share/cmake-3.18/Modules/FindBoost.cmake:1311 (_Boost_COMPONENT_DEPENDENCIES)
  /home/jbosch/LSST/lsstsw/miniconda/envs/ndarray/share/cmake-3.18/Modules/FindBoost.cmake:1919 (_Boost_MISSING_DEPENDENCIES)
  tests/CMakeLists.txt:11 (find_package)


-- Found Boost: /home/jbosch/LSST/lsstsw/miniconda/envs/ndarray/include (found version "1.74.0") found components: unit_test_framework 
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for one of the modules 'fftw3'
-- Found PythonInterp: /home/jbosch/LSST/lsstsw/miniconda/envs/ndarray/bin/python (found version "3.8.5") 
-- Found PythonLibs: /home/jbosch/LSST/lsstsw/miniconda/envs/ndarray/lib/libpython3.8.so (found version "3.8.5") 
-- Found PythonLibs: /home/jbosch/LSST/lsstsw/miniconda/envs/ndarray/lib/libpython3.8.so
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- Found pybind11: /home/jbosch/LSST/lsstsw/miniconda/envs/ndarray/include (found version "2.6.1" )
-- Configuring done
-- Generating done
-- Build files have been written to: /home/jbosch/ndarray/ndarray/build
```
Despite that, trying to build that seems fine as far as boost goes, but I still run into the same FFTW linking problem.  What's mysterious is that I do not see those messages in the [CI logs](https://github.com/ndarray/ndarray/pull/88/checks?check_run_id=1684130111), for what ought to be the same invocation.

Do you have any idea what's going on here?

Also, could you remove the `-D Boost_NO_BOOST_CMAKE=ON` from the CI script, and make sure it still works there?  CI should automatically be triggered when you push to the PR branch.

**Comment by mwittgen** [comment]
@TallJimbo does your conda environment have fftw=3.3.8 installed? The lib name is fftw3
./pkgs/fftw-3.3.8-h7b6447c_3/lib/cmake/fftw3

# packages in environment at /home/wittgen/miniconda_py38:
#
# Name                    Version                   Build  Channel
fftw                      3.3.8                h7b6447c_3

**Comment by TallJimbo** [comment]
I've got a slightly different build hash, but the same fftw version:
```
$ conda list fftw
# packages in environment at /home/jbosch/LSST/lsstsw/miniconda/envs/ndarray:
#
# Name                    Version                   Build  Channel
fftw                      3.3.8           nompi_hfc0cae8_1114    conda-forge
```
but the plot thickens - the libraries installed by that _appear_ to have the wrong version number in their filenames:
```
$ ls $CONDA_PREFIX/lib/libfftw3* -l
-rw-rw-r-- 1 jbosch jbosch 4808426 Jan 15 14:47 lib/libfftw3.a
-rw-rw-r-- 1 jbosch jbosch 4864232 Jan 15 14:47 lib/libfftw3f.a
-rw-rw-r-- 2 jbosch jbosch   52982 Nov 22 12:53 lib/libfftw3f_omp.a
lrwxrwxrwx 1 jbosch jbosch      22 Jan 15 14:47 lib/libfftw3f_omp.so -> libfftw3f_omp.so.3.5.8
lrwxrwxrwx 1 jbosch jbosch      22 Jan 15 14:47 lib/libfftw3f_omp.so.3 -> libfftw3f_omp.so.3.5.8
-rwxrwxr-x 2 jbosch jbosch   36952 Nov 22 13:06 lib/libfftw3f_omp.so.3.5.8
lrwxrwxrwx 1 jbosch jbosch      18 Jan 15 14:47 lib/libfftw3f.so -> libfftw3f.so.3.5.8
lrwxrwxrwx 1 jbosch jbosch      18 Jan 15 14:47 lib/libfftw3f.so.3 -> libfftw3f.so.3.5.8
-rwxrwxr-x 1 jbosch jbosch 2358864 Jan 15 14:47 lib/libfftw3f.so.3.5.8
-rw-rw-r-- 2 jbosch jbosch   58612 Nov 22 12:53 lib/libfftw3f_threads.a
lrwxrwxrwx 1 jbosch jbosch      26 Jan 15 14:47 lib/libfftw3f_threads.so -> libfftw3f_threads.so.3.5.8
lrwxrwxrwx 1 jbosch jbosch      26 Jan 15 14:47 lib/libfftw3f_threads.so.3 -> libfftw3f_threads.so.3.5.8
-rwxrwxr-x 2 jbosch jbosch   42024 Nov 22 13:06 lib/libfftw3f_threads.so.3.5.8
-rw-rw-r-- 1 jbosch jbosch 2292666 Jan 15 14:47 lib/libfftw3l.a
-rw-rw-r-- 2 jbosch jbosch   52950 Nov 22 13:01 lib/libfftw3l_omp.a
lrwxrwxrwx 1 jbosch jbosch      22 Jan 15 14:47 lib/libfftw3l_omp.so -> libfftw3l_omp.so.3.5.8
lrwxrwxrwx 1 jbosch jbosch      22 Jan 15 14:47 lib/libfftw3l_omp.so.3 -> libfftw3l_omp.so.3.5.8
-rwxrwxr-x 2 jbosch jbosch   36952 Nov 22 13:06 lib/libfftw3l_omp.so.3.5.8
lrwxrwxrwx 1 jbosch jbosch      18 Jan 15 14:47 lib/libfftw3l.so -> libfftw3l.so.3.5.8
lrwxrwxrwx 1 jbosch jbosch      18 Jan 15 14:47 lib/libfftw3l.so.3 -> libfftw3l.so.3.5.8
-rwxrwxr-x 1 jbosch jbosch 1034752 Jan 15 14:47 lib/libfftw3l.so.3.5.8
-rw-rw-r-- 2 jbosch jbosch   58580 Nov 22 13:01 lib/libfftw3l_threads.a
lrwxrwxrwx 1 jbosch jbosch      26 Jan 15 14:47 lib/libfftw3l_threads.so -> libfftw3l_threads.so.3.5.8
lrwxrwxrwx 1 jbosch jbosch      26 Jan 15 14:47 lib/libfftw3l_threads.so.3 -> libfftw3l_threads.so.3.5.8
-rwxrwxr-x 2 jbosch jbosch   42024 Nov 22 13:06 lib/libfftw3l_threads.so.3.5.8
-rw-rw-r-- 2 jbosch jbosch   52840 Nov 22 12:57 lib/libfftw3_omp.a
lrwxrwxrwx 1 jbosch jbosch      21 Jan 15 14:47 lib/libfftw3_omp.so -> libfftw3_omp.so.3.5.8
lrwxrwxrwx 1 jbosch jbosch      21 Jan 15 14:47 lib/libfftw3_omp.so.3 -> libfftw3_omp.so.3.5.8
-rwxrwxr-x 2 jbosch jbosch   36904 Nov 22 13:06 lib/libfftw3_omp.so.3.5.8
lrwxrwxrwx 1 jbosch jbosch      17 Jan 15 14:47 lib/libfftw3.so -> libfftw3.so.3.5.8
lrwxrwxrwx 1 jbosch jbosch      17 Jan 15 14:47 lib/libfftw3.so.3 -> libfftw3.so.3.5.8
-rwxrwxr-x 1 jbosch jbosch 2304616 Jan 15 14:47 lib/libfftw3.so.3.5.8
-rw-rw-r-- 2 jbosch jbosch   58468 Nov 22 12:57 lib/libfftw3_threads.a
lrwxrwxrwx 1 jbosch jbosch      25 Jan 15 14:47 lib/libfftw3_threads.so -> libfftw3_threads.so.3.5.8
lrwxrwxrwx 1 jbosch jbosch      25 Jan 15 14:47 lib/libfftw3_threads.so.3 -> libfftw3_threads.so.3.5.8
-rwxrwxr-x 2 jbosch jbosch   37872 Nov 22 13:06 lib/libfftw3_threads.so.3.5.8
```
...so I tried to upgrade fftw (to 3.3.9, since I couldn't figure out how to tell conda to install exactly the version you mentioned).

But that fails the same way, and the lib suffixes are now `.so.3.6.9`, which makes me think that those suffixes aren't _actually_ supposed to match the version number, and that's a red herring.

I couldn't find the `./pkgs/fftw-3.3.8-h7b6447c_3/lib/cmake/fftw3` you referenced, though - what's that path relative to?

**Comment by mwittgen** [comment]
How do I setup your version of the conda environment? On what Linux distro? I assume this is your interactive build failing? My build was done on current LSST stack on CentOS7.as well as on a miniconda 3.8 stack with python 3.8.

**Comment by TallJimbo** [comment]
@mwittgen and I resolved my difficulties offline (or at least worked around them) by switching to conda-provided compilers in my local environment, and I think this is ready to go.  If this breaks ndarray's ability to find anyone's dependency installs, we'll try to fix that ASAP, but I'm happy to be converting any such problems from ndarray-specific problems to more general standard-cmake-usage problems with this PR.

**Pull request merged**
